---
title: aboriis-pi
description: Media stack
startUrl: /

theme: dark
color: slate
headerStyle: clean
hideVersion: true

layout:
  System:
    style: row
    columns: 3
  Monitoring:
    style: row
    columns: 3
  Libraries:
    style: row
    columns: 3
  Automation:
    style: row
    columns: 3
  Acquisition:
    style: row
    columns: 2
